name: storelytics_admin
description: "Storelytics Admin Panel - Platform Management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # Charts
  fl_chart: ^0.70.2

  # Utilities
  intl: ^0.20.2

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
